import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Routes, Route, Link, Navigate, useNavigate, useParams } from 'react-router-dom';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
const fields = [
  ['date_of_birth', 'Date of birth', 'date'], ['gender', 'Gender'], ['category', 'Category'], ['state', 'State'], ['district', 'District'], ['class_level', 'Class level'], ['institution', 'Institution'], ['course', 'Course'], ['family_income', 'Annual family income (₹)', 'number'], ['annual_percentage', 'Annual percentage', 'number'], ['disability_status', 'Disability status'], ['academic_year', 'Academic year']
];

async function request(path, options = {}) {
  const token = localStorage.getItem('token');
  const response = await fetch(`${API}${path}`, { headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers }, ...options });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) {
    if (response.status === 401) localStorage.clear();
    throw new Error(data.error || 'Request failed');
  }
  return data;
}

function Layout({ children }) {
  const user = JSON.parse(localStorage.getItem('user') || 'null'); const nav = useNavigate();
  return <><header><Link className="brand" to={user?.role === 'ADMIN' ? '/admin/dashboard' : '/student/dashboard'}>Scholarship Portal</Link>{user && <nav><Link to="/student/dashboard">Dashboard</Link><Link to="/student/profile">My profile</Link><Link to="/student/scholarships">Scholarships</Link>{user.role === 'ADMIN' && <Link to="/admin/dashboard">Admin</Link>}<button onClick={() => { localStorage.clear(); nav('/login'); }}>Sign out</button></nav>}</header><main>{children}</main></>;
}

function Notice({ error, message }) { return <>{error && <p className="notice error" role="alert">{error}</p>}{message && <p className="notice success">{message}</p>}</>; }
function Loading() { return <p className="muted">Loading…</p>; }

function Auth({ register = false }) {
  const [data, setData] = useState({ name: '', email: register ? '' : 'student@example.com', password: register ? '' : 'Password123!' }); const [error, setError] = useState(''); const nav = useNavigate();
  const submit = async event => { event.preventDefault(); setError(''); try { const result = await request(`/auth/${register ? 'register' : 'login'}`, { method: 'POST', body: JSON.stringify(data) }); localStorage.setItem('token', result.token); localStorage.setItem('user', JSON.stringify(result.user)); nav(result.user.role === 'ADMIN' ? '/admin/dashboard' : '/student/dashboard'); } catch (err) { setError(err.message); } };
  return <Layout><section className="auth card"><h1>{register ? 'Create your account' : 'Welcome back'}</h1><p>{register ? 'Start checking scholarship eligibility.' : 'Use the demo student account or your own account.'}</p><form onSubmit={submit}>{register && <label>Full name<input autoComplete="name" required value={data.name} onChange={e => setData({ ...data, name: e.target.value })} /></label>}<label>Email<input type="email" autoComplete="email" required value={data.email} onChange={e => setData({ ...data, email: e.target.value })} /></label><label>Password<input type="password" autoComplete={register ? 'new-password' : 'current-password'} minLength="8" required value={data.password} onChange={e => setData({ ...data, password: e.target.value })} /></label><Notice error={error} /><button className="primary">{register ? 'Register' : 'Sign in'}</button></form><p>{register ? <Link to="/login">Already have an account? Sign in</Link> : <Link to="/register">Need an account? Register</Link>}</p><small>Demo student: student@example.com / Password123!</small></section></Layout>;
}

function useScholarships() { const [items, setItems] = useState([]), [error, setError] = useState(''), [loading, setLoading] = useState(true); useEffect(() => { request('/scholarships').then(setItems).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []); return { items, error, loading }; }
function Dashboard() { const { items, error, loading } = useScholarships(); const groups = ['ELIGIBLE', 'POSSIBLY_ELIGIBLE', 'NOT_ELIGIBLE']; return <Layout><h1>Your scholarship dashboard</h1><p className="muted">Eligibility is based on the transparent rules recorded in this portal. Always verify the official notice.</p><Notice error={error} />{loading ? <Loading /> : <><div className="stats">{groups.map(group => <div className="card" key={group}><strong>{items.filter(item => item.eligibility.status === group).length}</strong><span className={`badge ${group}`}>{group.replace('_', ' ')}</span></div>)}</div><h2>Upcoming opportunities</h2><ScholarshipList items={items} /></>}</Layout>; }
function ScholarshipList({ items }) { return <div className="list">{items.length ? items.map(s => <article className="card scholarship" key={s.id}><div><h3>{s.title}</h3><p>{s.provider}</p><p>{s.description}</p><small>Deadline: {s.deadline}</small></div><div><span className={`badge ${s.eligibility.status}`}>{s.eligibility.status.replace('_', ' ')}</span><Link className="button" to={`/student/scholarships/${s.id}`}>View details</Link></div></article>) : <p className="empty">No scholarships match your search.</p>}</div>; }
function Directory() { const { items, error, loading } = useScholarships(); const [query, setQuery] = useState(''); const selected = items.filter(s => `${s.title} ${s.provider}`.toLowerCase().includes(query.toLowerCase())); return <Layout><h1>Scholarships</h1><label className="search">Search by scholarship or provider<input value={query} onChange={e => setQuery(e.target.value)} /></label><Notice error={error} />{loading ? <Loading /> : <ScholarshipList items={selected} />}</Layout>; }

function Detail() { const { id } = useParams(); const [scholarship, setScholarship] = useState(null), [error, setError] = useState(''); useEffect(() => { request(`/scholarships/${id}`).then(setScholarship).catch(e => setError(e.message)); }, [id]); const updateChecklist = async (document, status) => { try { await request(`/student/checklists/${document.id}`, { method: 'PUT', body: JSON.stringify({ status }) }); setScholarship({ ...scholarship, documents: scholarship.documents.map(d => d.id === document.id ? { ...d, checklist_status: status } : d) }); } catch (err) { setError(err.message); } }; if (error && !scholarship) return <Layout><Notice error={error} /><Link to="/student/scholarships">Back to scholarships</Link></Layout>; if (!scholarship) return <Layout><Loading /></Layout>; return <Layout><Link to="/student/scholarships">← Back to scholarships</Link><h1>{scholarship.title}</h1><p>{scholarship.provider} · Deadline: {scholarship.deadline}</p><p>{scholarship.description}</p><Notice error={error} /><section className="card"><h2>Eligibility result</h2><Eligibility id={id} /></section><section className="card"><h2>Required documents</h2>{scholarship.documents.map(document => <div className="document" key={document.id}><span><b>{document.name}</b><small>{document.description}</small></span><label className="sr-only" htmlFor={`document-${document.id}`}>Status for {document.name}</label><select id={`document-${document.id}`} value={document.checklist_status} onChange={e => updateChecklist(document, e.target.value)}><option value="NOT_READY">Not ready</option><option value="READY">Ready</option><option value="UPLOADED">Uploaded</option></select></div>)}</section><a className="button" href={scholarship.official_notice_url} target="_blank" rel="noreferrer">View original notice</a></Layout>; }
function Eligibility({ id }) { const [result, setResult] = useState(null), [error, setError] = useState(''); useEffect(() => { request(`/scholarships/${id}/eligibility`).then(setResult).catch(e => setError(e.message)); }, [id]); if (error) return <Notice error={error} />; if (!result) return <Loading />; return <><span className={`badge ${result.status}`}>{result.status.replace('_', ' ')}</span>{result.rules.map(rule => <div className={`rule ${rule.status.toLowerCase()}`} key={rule.ruleId}><b>{rule.status === 'PASS' ? '✓' : rule.status === 'MISSING' ? '?' : '×'} {rule.label}</b><span>{rule.status === 'MISSING' ? 'Not provided' : `Your value: ${Array.isArray(rule.actualValue) ? rule.actualValue.join(', ') : rule.actualValue}`}</span><small>Required: {Array.isArray(rule.expectedValue) ? rule.expectedValue.join(' to ') : String(rule.expectedValue)}</small></div>)}<p><b>Reason:</b> {result.reason}</p></>; }

function Profile() { const [data, setData] = useState({}), [message, setMessage] = useState(''), [error, setError] = useState(''), [loading, setLoading] = useState(true); useEffect(() => { request('/profile').then(setData).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []); const save = async event => { event.preventDefault(); setError(''); setMessage(''); try { await request('/profile', { method: 'PUT', body: JSON.stringify(data) }); setMessage('Profile saved successfully. Your eligibility results are now updated.'); } catch (err) { setError(err.message); } }; return <Layout><h1>My profile</h1><p>Complete your information for accurate scholarship results.</p>{loading ? <Loading /> : <form className="card form-grid" onSubmit={save}>{fields.map(([key, label, type = 'text']) => <label key={key}>{label}<input type={type} min={type === 'number' ? '0' : undefined} step={key === 'annual_percentage' ? '0.01' : undefined} value={data[key] ?? ''} onChange={e => setData({ ...data, [key]: e.target.value })} /></label>)}<Notice error={error} message={message} /><button className="primary">Save profile</button></form>}</Layout>; }

function Admin() { const [items, setItems] = useState([]), [error, setError] = useState(''), [loading, setLoading] = useState(true); const load = () => request('/admin/scholarships').then(setItems).catch(e => setError(e.message)).finally(() => setLoading(false)); useEffect(load, []); const toggle = async scholarship => { try { const status = scholarship.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE'; await request(`/admin/scholarships/${scholarship.id}/status`, { method: 'PATCH', body: JSON.stringify({ status }) }); setItems(items.map(item => item.id === scholarship.id ? { ...item, status } : item)); } catch (err) { setError(err.message); } }; return <Layout><h1>Administrator dashboard</h1><p>Manage recorded scholarships and their availability.</p><CreateScholarship onCreated={newItem => setItems([newItem, ...items])} /><Notice error={error} />{loading ? <Loading /> : <div className="list">{items.map(s => <article className="card scholarship" key={s.id}><div><h3>{s.title}</h3><p>{s.provider}</p><small>Deadline: {s.deadline}</small></div><div><span className={`badge ${s.status === 'ACTIVE' ? 'ELIGIBLE' : 'NOT_ELIGIBLE'}`}>{s.status}</span><button onClick={() => toggle(s)}>{s.status === 'ACTIVE' ? 'Deactivate' : 'Activate'}</button></div></article>)}</div>}</Layout>; }
function CreateScholarship({ onCreated }) { const [open, setOpen] = useState(false), [data, setData] = useState({ title: '', provider: '', description: '', deadline: '', official_notice_url: '' }), [error, setError] = useState(''); const submit = async event => { event.preventDefault(); setError(''); try { const item = await request('/admin/scholarships', { method: 'POST', body: JSON.stringify(data) }); onCreated(item); setData({ title: '', provider: '', description: '', deadline: '', official_notice_url: '' }); setOpen(false); } catch (err) { setError(err.message); } }; return <section className="card"><div className="section-heading"><div><h2>Add a scholarship</h2><p className="muted">Create the scholarship record first; detailed rules can be added through the API.</p></div><button type="button" className="primary" onClick={() => setOpen(!open)}>{open ? 'Cancel' : 'Add scholarship'}</button></div>{open && <form className="form-grid" onSubmit={submit}><label>Title<input required value={data.title} onChange={e => setData({ ...data, title: e.target.value })} /></label><label>Provider<input required value={data.provider} onChange={e => setData({ ...data, provider: e.target.value })} /></label><label>Deadline<input type="date" required value={data.deadline} onChange={e => setData({ ...data, deadline: e.target.value })} /></label><label>Official notice URL<input type="url" required value={data.official_notice_url} onChange={e => setData({ ...data, official_notice_url: e.target.value })} /></label><label className="wide">Description<textarea required value={data.description} onChange={e => setData({ ...data, description: e.target.value })} /></label><Notice error={error} /><button className="primary">Create scholarship</button></form>}</section>; }
function Protected({ children, admin = false }) { const user = JSON.parse(localStorage.getItem('user') || 'null'); return !user ? <Navigate to="/login" /> : admin && user.role !== 'ADMIN' ? <Navigate to="/student/dashboard" /> : children; }
function App() { return <Routes><Route path="/login" element={<Auth />} /><Route path="/register" element={<Auth register />} /><Route path="/student/dashboard" element={<Protected><Dashboard /></Protected>} /><Route path="/student/profile" element={<Protected><Profile /></Protected>} /><Route path="/student/scholarships" element={<Protected><Directory /></Protected>} /><Route path="/student/scholarships/:id" element={<Protected><Detail /></Protected>} /><Route path="/admin/dashboard" element={<Protected admin><Admin /></Protected>} /><Route path="*" element={<Navigate to="/login" />} /></Routes>; }
createRoot(document.getElementById('root')).render(<BrowserRouter><App /></BrowserRouter>);
